// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqfpwbyjxrmpzfqrmocy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZnB3YnlqeHJtcHpmcXJtb2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTEwMzMsImV4cCI6MjA1Nzg2NzAzM30.8Vi-9Uy7x0n713-yYf9Ylulg2nVOZYAXaDVg6qXwxUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);